### PR TITLE
feat: add app & admin cookie secure variable to dashboard

### LINKED ISSUE #233: feat(dashboard): Allow insecure cookies
**Feature Description**

Check following PR: https://github.com/authorizerdev/authorizer/pull/229
Add support for `APP_COOKIE_SECURE` & `ADMIN_COOKIE_SECURE` in features section
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jerebtw**
- [ ] Generate graphql (i don't work on my PC (Windows))

#### What does this PR do?

Add the envs to dashboard

#### Which issue(s) does this PR fix?

fixes #233

### CODE REVIEW

**Comment by lakhansamani** [comment]
@jerebtw can you pull latest `main` branch and try using following command

```
make generate
```

OR

```
cd server
go run github.com/99designs/gqlgen generate
```

**Comment by jerebtw** [comment]
> @jerebtw can you pull latest `main` branch and try using following command
> 
> ```
> make generate
> ```
> 
> OR
> 
> ```
> cd server
> go run github.com/99designs/gqlgen generate
> ```

Now it works :

**Comment by jerebtw** [comment]
But it still doesn't work (The GraphQL query)

**Comment by lakhansamani** [comment]
@jerebtw I checked the PR,
You need to add those values to the resolver

https://github.com/authorizerdev/authorizer/blob/main/server/resolvers/env.go

**Review by lakhansamani — APPROVED** [review]

**Pull request merged**
