### PR TITLE
feat: Add a option to disable httpOnly cookies

### PR DESCRIPTION
**Pull request by ruessej**
#### What does this PR do?

Adds 2 envs to disable httpOnly cookies

#### Which issue(s) does this PR fix?

fixes https://github.com/authorizerdev/authorizer/issues/227

#### If this PR affects any API reference documentation, please share the updated endpoint references

Probably the envs section?

### CODE REVIEW

**Comment by lakhansamani** [comment]
This also needs to be supported in dashboard, so I will create issue for that and will add it

**Comment by ruessej** [comment]
When the admin env is true or empty the same problem as before will happen:

image

When the admin env is false then this will happen:

image

**Comment by lakhansamani** [comment]
Thanks this is helpful, I will merge and release it later today

**Comment by ruessej** [comment]
Thanks :)

**Review by lakhansamani — APPROVED** [review]

**Comment by lakhansamani** [comment]
@ruessej thank you for your contribution. Changes are part of 1.1.5 release

**Pull request merged**
