### PR TITLE
Feat/return user info on invitation

### PR DESCRIPTION
**Pull request by MussieT**
#### What does this PR do?
Adds the functionality to return user information (id, email) on the invitation.

#### Which issue(s) does this PR fix?
https://github.com/authorizerdev/authorizer/issues/345

#### If this PR affects any API reference documentation, please share the updated endpoint references
https://github.com/authorizerdev/docs/compare/main...MussieT:docs:patch-1

**Preview**
Screencast 2023-04-19 16 09 28

### CODE REVIEW

**Review by lakhansamani — CHANGES_REQUESTED** [review]
@MussieT can you also update the test for this particular resolver
https://github.com/authorizerdev/authorizer/blob/e822b6f31a24ca0a899115164119a26f78694edb/server/test/invite_member_test.go#L47

Overall it looks good to me

**Comment by MussieT** [comment]
@lakhansamani Thanks for the response. But one question, the written test for the `invite_members` implementation checks whether the response is not `nil`. Should I modify it to check if the response contains both the `message` and `users`?

**Comment by lakhansamani** [comment]
Yes that would be better test earlier response just had message now its good idea to check if it has expected users or not

**Comment by MussieT** [comment]
@lakhansamani updated the test.

**Review by lakhansamani — APPROVED** [review]
LGTM

**Comment by lakhansamani** [comment]
Thanks @MussieT

**Comment by MussieT** [comment]
Appreciated the response @lakhansamani , planned to have more contributions soon.

**Pull request merged**
