### PR TITLE
Feat/couchbase db support

### PR DESCRIPTION
**Pull request by manojown**
#### What does this PR do?
DynamoDb Support - #242

#### If this PR affects any API reference documentation, please share the updated endpoint references
  Providing the couchbase support

#### If this PR affects any API reference documentation, please share the updated endpoint references
   NO
#### Env Require

1.  DATABASE_URL - Couchbase DB URL
2. DATABASE_USERNAME - DB User name
3. DATABASE_PASSWORD - DB Password
4. COUCHBASE_BUCKET - Couchbase Bucket name
5. COUCHBASE_SCOPE -  Couchbase Scope name or that can be `_default` as well
6. DATABASE_TYPE - `couchbase`

### CODE REVIEW

**Comment by lakhansamani** [comment]
@manojown this PR will need a newly introduced db provider method called `GetUserByPhoneNumber`

https://github.com/authorizerdev/authorizer/blob/1eb8965f98dcea421ab99b5626b46afe930b9c79/server/db/providers/providers.go#L22

**Comment by lakhansamani** [comment]
[discussion]:
What if we set by default and not allow this env vars
`COUCHBASE_BUCKET` -> `authorizer`
`COUCHBASE_SCOPE` -> `authorizer`

Any side effects you see for them?

**Comment by manojown** [comment]
@lakhansamani  There is a problem if someone already has a database set up with some scope and wants to switch to an authoriser. In this case, they must make changes to their database and need to create a default scope. WYT?

**Comment by manojown** [comment]
> @manojown this PR will need a newly introduced db provider method called `GetUserByPhoneNumber`
> 
> 
> 
> https://github.com/authorizerdev/authorizer/blob/1eb8965f98dcea421ab99b5626b46afe930b9c79/server/db/providers/providers.go#L22
> 
> 
> 
> 
Ok, I'll add this.

**Comment by manojown** [comment]
@lakhansamani Is there any additional effect of `GetUserByPhoneNumber`, i.e. anything else I could have missed?

**Comment by lakhansamani** [comment]
@manojown no usage of `GetUserByPhoneNumber` is already covered.

**Pull request merged**
